
use customer_behavior;


-- Q1.What is the total revenue generated by male vs female?
select gender, sum(purchase_amount) as revenue
from shopping_data
group by gender;

-- Q2.Which customer used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount 
from shopping_data
where discount_applied ='Yes' and purchase_amount >=(select avg(purchase_amount) from shopping_data);

-- Q3.Whixh are the top 5 products with the highest review ratings?
select item_purchased, round(avg(review_rating),1) as "Average_Product_Rating"
from shopping_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4.Compare the average purchase amount between standard and express shipping.
select shipping_type, round(avg(purchase_amount),2)
from shopping_data
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5.Do subscribed customers spend more? compare average customer ....alter
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from shopping_data
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6.which 5 products have the highest percentage of  purchases with discount...
select item_purchased,
ROUND(100 * sum(case when discount_applied ='Yes' THEN 1 ELSE 0 END) / count(*), 2) 
as discount_rate
from shopping_data
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customer into new, returning , and loyal based on their total 
-- number of previous purchases...alter
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM shopping_data)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM shopping_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as total_revenue
from shopping_data
group by age_group 
order by total_revenue desc;

